myConferenceWithEF/myConferenceWithEF/Controllers/ConferenceUsersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using myConferenceWithEF.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Models;
using Services;
using static myConferenceWithEF.ViewModels.ConferenceUserViewModel;

namespace myConferenceWithEF.Controllers
{
    public class ConferenceUsersController : Controller
    {
        //private readonly EfRepository<ConferenceUser> _efRepository;
        private readonly IRepository<ConferenceUser> _conferenceUserRepository;
        private readonly IRepository<City> _citiesRepository;

        public ConferenceUsersController(ConferenceContext context)
        {
            _conferenceUserRepository = new EfRepository<ConferenceUser>(context);
            _citiesRepository = new EfRepository<City>(context);
        }

        // GET: ConferenceUsers
        public async Task<IActionResult> Index()
        {

            return View(_conferenceUserRepository.GetAllToView<ConferenceUserViewModel>());
        }

        // GET: ConferenceUsers/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conferenceUser = _conferenceUserRepository.GetSingle((Guid)id);
            if (conferenceUser == null)
            {
                return NotFound();
            }

            return View(conferenceUser);
        }

        // GET: ConferenceUsers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ConferenceUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[Bind("FirstName,LastName,Email,AvatarPath")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ConferenceUserViewModel conferenceUserVM, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                var conferenceUser = conferenceUserVM.ConvertToUser();
                _conferenceUserRepository.Add(conferenceUser);

                if (file.Length > 0)
                {
                    string path = $"wwwroot/images/{conferenceUserVM.AvatarPath}";
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        file.CopyTo(stream);
                    }
                }
            }
            return RedirectToAction(nameof(Index));
        }

        public ActionResult GetSingle()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetSingleToDelete(EditDeleteConferenceUserViewModel conferenceUser)
        {
            var selectedUser = _conferenceUserRepository
                .GetAll()
                .FirstOrDefault(f =>
                 f.FirstName == conferenceUser.FirstName && f.LastName == conferenceUser.LastName);
            var ID = selectedUser.ID;
            return RedirectToAction("Delete", new { ID });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetSingleToUpdate(EditDeleteConferenceUserViewModel conferenceUser)
        {
            var selectedUser = _conferenceUserRepository
                .GetAll()
                .FirstOrDefault(f =>
                    f.FirstName == conferenceUser.FirstName && f.LastName == conferenceUser.LastName);
            var ID = selectedUser.ID;
            return RedirectToAction("Edit", new { ID });
        }
        // GET: ConferenceUsers/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conferenceUser = _conferenceUserRepository.GetSingle((Guid)id);
            if (conferenceUser == null)
            {
                return NotFound();
            }
            return View(conferenceUser);
        }

        // POST: ConferenceUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[Bind("FirstName,LastName,Email,AvatarPath")] 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ConferenceUser conferenceUser)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _conferenceUserRepository.Edit(conferenceUser);
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(conferenceUser);
        }

        // GET: ConferenceUsers/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conferenceUser = _conferenceUserRepository.GetSingle((Guid)id);
            if (conferenceUser == null)
            {
                return NotFound();
            }

            return View(conferenceUser);
        }

        // POST: ConferenceUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var conferenceUser = _conferenceUserRepository.GetSingle(id);
            _conferenceUserRepository.Delete(conferenceUser);
            return RedirectToAction(nameof(Index));
        }
    }
}

myConferenceWithEF/myConferenceWithEF/Views/ConferenceUsers/Create.cshtml
@model myConferenceWithEF.ViewModels.ConferenceUserViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>ConferenceUser</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-controller="ConferenceUsers" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div>
                <label>Avatar Path</label>
                <input type="file" name="file" class="btn-default" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

myConferenceWithEF/myConferenceWithEF/Views/ConferenceUsers/Delete.cshtml
@model Models.ConferenceUser

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ConferenceUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AvatarPath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AvatarPath)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

myConferenceWithEF/myConferenceWithEF/Views/ConferenceUsers/Details.cshtml
@model Models.ConferenceUser

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ConferenceUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AvatarPath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AvatarPath)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

myConferenceWithEF/myConferenceWithEF/Views/ConferenceUsers/Edit.cshtml
@model Models.ConferenceUser

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>ConferenceUser</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AvatarPath" class="control-label"></label>
                <input asp-for="AvatarPath" class="form-control" />
                <span asp-validation-for="AvatarPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

myConferenceWithEF/myConferenceWithEF/Views/ConferenceUsers/GetSingle.cshtml
@model myConferenceWithEF.ViewModels.EditDeleteConferenceUserViewModel

@{
    ViewData["Title"] = "GetSingle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetSingle</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="row">
    <div class="col-md-4">
        <form asp-action="GetSingleToDelete">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="GetSingleToUpdate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

myConferenceWithEF/myConferenceWithEF/Views/ConferenceUsers/Index.cshtml
@model IEnumerable<myConferenceWithEF.ViewModels.ConferenceUserViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    Picture
                </th>
                <th>
                    FirstName
                </th>
                <th>
                    LastName
                </th>
                <th>
                    E-mail
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
    <tr>
        <td>
            <img src="~/images/@item.AvatarPath" class="img-responsive" style="width: 25px; height: 25px; margin-right: auto; margin-left: auto; display: block " />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            <a asp-action="GetSingle">Choose user</a> |
        </td>
    </tr>
}
    </tbody>
</table>