myConferenceWithEF/myConferenceWithEF/Controllers/ConferenceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Models;
using Services;

namespace myConferenceWithEF.Controllers
{
    public class ConferenceController : Controller
    {
        private readonly ConferenceContext _context;

        public ConferenceController(ConferenceContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            
            ViewBag.Message = "Chujdupakurwacipa";
            return View();
        }
       
        [HttpGet]
        public IActionResult SaveUser()
        {
            //ConferenceList.GuestList
           
            return View(_context.ConferenceUsers.ToList());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveUser(ConferenceUser user, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string path = string.Empty;
                if (file.Length > 0)
                {
                    path = $"wwwroot/images/{file.FileName}";
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        file.CopyTo(stream);
                    }
                }
                user.AvatarPath = $"{file.FileName}";

                _context.ConferenceUsers.Add(user);
                _context.SaveChanges();
                TempData["ResultMessage"] = "Dodanie uzytkownika zakonczone sukcesem!";
                return RedirectToAction(nameof(SaveUser));
            }
            return View(user);
        }
    }
}

myConferenceWithEF/myConferenceWithEF/Views/Conference/SaveUser.cshtml
@model IEnumerable<Models.ConferenceUser>

@{
    ViewData["Title"] = "SaveUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SaveUser</h2>

<form method="post" enctype="multipart/form-data" asp-controller="Conference" asp-action="SaveUser">
    <div class="form-group">
        <div class="col-md-10">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <p>Uzupełnij formularz by dodać członka konferencji</p>
            <label>First Name</label><br />
            <input type="text" name="FirstName" /><br />
            <label>Last Name</label><br />
            <input type="text" name="LastName" /><br />
            <label>Email</label><br />
            <input type="text" name="Email" /><br />
            <br />
            <p>Wyślij plik tutaj:</p>
            <input type="file" name="file" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Zapisz" />
        </div>
    </div>
</form>
<br />

<div class="col-md-6 col-sm-12" style="align-content: center">
    <table class=" table-condensed table-striped table-bordered table-responsive text-center">
        <thead>
            <tr>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.AvatarPath)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.Email)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var participant in Model)
            {
                <tr>
                    <td>
                        <img src="~/images/@participant.AvatarPath" class="img-responsive" style="width: 25px; height: 25px; margin-right: auto; margin-left: auto; display: block " />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => participant.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => participant.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => participant.Email)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>